---
kind: pipeline
type: ssh
name: default

server:
  host:
    from_secret: host
  user:
    from_secret: username
  password:
    from_secret: password

steps:
- name: update
  commands:
  - cd /mydata/nginx/html/MaskWolfNote
  - git pull

trigger:
  branch:
  - main
  event:
  - push
  - pull_request
